mod attribute;
mod auto_type_data;
mod binaries;
mod binary_reference;
mod boolean;
mod custom_data;
mod custom_icons;
mod deleted_object;
mod doctype;
mod element;
mod entry;
pub mod format_xml;
mod group;
mod instant;
pub mod keyfile_xml;
mod namespace;
mod node;
mod node_ext;
mod print_options;
mod text;
mod time_data;
mod utils;
mod xml_builder;
mod xml_version;

pub use attribute::{Attribute, AttributeValue, UnsafeValue, unsafe_value};
pub use auto_type_data::{marshal_auto_type_data, unmarshal_auto_type_data};
pub use binaries::{marshal_binary_data, unmarshal_binaries};
pub use binary_reference::{marshal_binary_reference, unmarshal_binary_reference};
pub use boolean::{BoolXmlExt, bool_to_xml_string};
pub use custom_data::{marshal_custom_data, unmarshal_custom_data};
pub use custom_icons::{marshal_custom_icons, unmarshal_custom_icons};
pub use deleted_object::{marshal_deleted_object, unmarshal_deleted_object};
pub use doctype::Doctype;
pub use element::Element;
pub use entry::{InnerStream, marshal_entry, unmarshal_entries, unmarshal_entry};
pub use group::{marshal_group, unmarshal_group};
pub use instant::{
    EPOCH_SECONDS_FROM_AD, NodeInstantExt, XmlInstantError, marshal_instant, parse_instant,
};
pub use namespace::Namespace;
pub use node::Node;
pub use node_ext::{NodeValueError, NodeXmlExt};
pub use print_options::PrintOptions;
pub use text::{CDataElement, Comment, ProcessingInstructionElement, TextElement};
pub use time_data::{marshal_time_data, unmarshal_time_data};
pub use utils::{build_name, escape_value, reference_character};
pub use xml_builder::{XmlParseError, node, parse_str, xml};
pub use xml_version::XmlVersion;
